apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: base
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
  publishNotReadyAddresses: true  # pod가 ready 아니어도 DNS 응답
