apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: base
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless — StatefulSet DNS 안정성
